export interface Country {
  id: string; // ISO Alpha-3
  numeric: string; // ISO Numeric
  name: string;
  aliases?: string[];
}

export const COUNTRIES: Country[] = [
  { id: "AFG", numeric: "004", name: "Afghanistan" },
  { id: "ALA", numeric: "248", name: "Åland Islands" },
  { id: "ALB", numeric: "008", name: "Albania" },
  { id: "DZA", numeric: "012", name: "Algeria" },
  { id: "ASM", numeric: "016", name: "American Samoa" },
  { id: "AND", numeric: "020", name: "Andorra" },
  { id: "AGO", numeric: "024", name: "Angola" },
  { id: "AIA", numeric: "660", name: "Anguilla" },
  { id: "ATA", numeric: "010", name: "Antarctica" },
  { id: "ATG", numeric: "028", name: "Antigua and Barbuda" },
  { id: "ARG", numeric: "032", name: "Argentina" },
  { id: "ARM", numeric: "051", name: "Armenia" },
  { id: "ABW", numeric: "533", name: "Aruba" },
  { id: "AUS", numeric: "036", name: "Australia" },
  { id: "AUT", numeric: "040", name: "Austria" },
  { id: "AZE", numeric: "031", name: "Azerbaijan" },
  { id: "BHS", numeric: "044", name: "Bahamas" },
  { id: "BHR", numeric: "048", name: "Bahrain" },
  { id: "BGD", numeric: "050", name: "Bangladesh" },
  { id: "BRB", numeric: "052", name: "Barbados" },
  { id: "BLR", numeric: "112", name: "Belarus" },
  { id: "BEL", numeric: "056", name: "Belgium" },
  { id: "BLZ", numeric: "084", name: "Belize" },
  { id: "BEN", numeric: "204", name: "Benin" },
  { id: "BMU", numeric: "060", name: "Bermuda" },
  { id: "BTN", numeric: "064", name: "Bhutan" },
  { id: "BOL", numeric: "068", name: "Bolivia", aliases: ["Bolivia, Plurinational State of"] },
  { id: "BES", numeric: "535", name: "Bonaire, Sint Eustatius and Saba" },
  { id: "BIH", numeric: "070", name: "Bosnia and Herzegovina" },
  { id: "BWA", numeric: "072", name: "Botswana" },
  { id: "BVT", numeric: "074", name: "Bouvet Island" },
  { id: "BRA", numeric: "076", name: "Brazil" },
  { id: "IOT", numeric: "086", name: "British Indian Ocean Territory" },
  { id: "BRN", numeric: "096", name: "Brunei", aliases: ["Brunei Darussalam"] },
  { id: "BGR", numeric: "100", name: "Bulgaria" },
  { id: "BFA", numeric: "854", name: "Burkina Faso" },
  { id: "BDI", numeric: "108", name: "Burundi" },
  { id: "CPV", numeric: "132", name: "Cabo Verde", aliases: ["Cape Verde"] },
  { id: "KHM", numeric: "116", name: "Cambodia" },
  { id: "CMR", numeric: "120", name: "Cameroon" },
  { id: "CAN", numeric: "124", name: "Canada" },
  { id: "CYM", numeric: "136", name: "Cayman Islands" },
  { id: "CAF", numeric: "140", name: "Central African Republic" },
  { id: "TCD", numeric: "148", name: "Chad" },
  { id: "CHL", numeric: "152", name: "Chile" },
  { id: "CHN", numeric: "156", name: "China" },
  { id: "CXR", numeric: "162", name: "Christmas Island" },
  { id: "CCK", numeric: "166", name: "Cocos (Keeling) Islands" },
  { id: "COL", numeric: "170", name: "Colombia" },
  { id: "COM", numeric: "174", name: "Comoros" },
  { id: "COG", numeric: "178", name: "Congo", aliases: ["Republic of the Congo", "Congo-Brazzaville"] },
  { id: "COD", numeric: "180", name: "Congo, Democratic Republic of the", aliases: ["DRC", "DR Congo", "Congo-Kinshasa"] },
  { id: "COK", numeric: "184", name: "Cook Islands" },
  { id: "CRI", numeric: "188", name: "Costa Rica" },
  { id: "CIV", numeric: "384", name: "Côte d'Ivoire", aliases: ["Ivory Coast"] },
  { id: "HRV", numeric: "191", name: "Croatia" },
  { id: "CUB", numeric: "192", name: "Cuba" },
  { id: "CUW", numeric: "531", name: "Curaçao" },
  { id: "CYP", numeric: "196", name: "Cyprus" },
  { id: "CZE", numeric: "203", name: "Czech Republic", aliases: ["Czechia", "Chez republic", "Chez"] },
  { id: "DNK", numeric: "208", name: "Denmark" },
  { id: "DJI", numeric: "262", name: "Djibouti" },
  { id: "DMA", numeric: "212", name: "Dominica" },
  { id: "DOM", numeric: "214", name: "Dominican Republic" },
  { id: "ECU", numeric: "218", name: "Ecuador" },
  { id: "EGY", numeric: "818", name: "Egypt" },
  { id: "SLV", numeric: "222", name: "El Salvador" },
  { id: "GNQ", numeric: "226", name: "Equatorial Guinea" },
  { id: "ERI", numeric: "232", name: "Eritrea" },
  { id: "EST", numeric: "233", name: "Estonia" },
  { id: "SWZ", numeric: "748", name: "Eswatini", aliases: ["Swaziland"] },
  { id: "ETH", numeric: "231", name: "Ethiopia" },
  { id: "FLK", numeric: "238", name: "Falkland Islands (Malvinas)" },
  { id: "FRO", numeric: "234", name: "Faroe Islands" },
  { id: "FJI", numeric: "242", name: "Fiji" },
  { id: "FIN", numeric: "246", name: "Finland" },
  { id: "FRA", numeric: "250", name: "France" },
  { id: "GUF", numeric: "254", name: "French Guiana" },
  { id: "PYF", numeric: "258", name: "French Polynesia" },
  { id: "ATF", numeric: "260", name: "French Southern Territories" },
  { id: "GAB", numeric: "266", name: "Gabon" },
  { id: "GMB", numeric: "270", name: "Gambia" },
  { id: "GEO", numeric: "268", name: "Georgia" },
  { id: "DEU", numeric: "276", name: "Germany" },
  { id: "GHA", numeric: "288", name: "Ghana" },
  { id: "GIB", numeric: "292", name: "Gibraltar" },
  { id: "GRC", numeric: "300", name: "Greece" },
  { id: "GRL", numeric: "304", name: "Greenland" },
  { id: "GRD", numeric: "308", name: "Grenada" },
  { id: "GLP", numeric: "312", name: "Guadeloupe" },
  { id: "GUM", numeric: "316", name: "Guam" },
  { id: "GTM", numeric: "320", name: "Guatemala" },
  { id: "GGY", numeric: "831", name: "Guernsey" },
  { id: "GIN", numeric: "324", name: "Guinea" },
  { id: "GNB", numeric: "624", name: "Guinea-Bissau" },
  { id: "GUY", numeric: "328", name: "Guyana" },
  { id: "HTI", numeric: "332", name: "Haiti" },
  { id: "HMD", numeric: "334", name: "Heard Island and McDonald Islands" },
  { id: "VAT", numeric: "336", name: "Vatican City", aliases: ["Holy See"] },
  { id: "HND", numeric: "340", name: "Honduras" },
  { id: "HKG", numeric: "344", name: "Hong Kong" },
  { id: "HUN", numeric: "348", name: "Hungary" },
  { id: "ISL", numeric: "352", name: "Iceland" },
  { id: "IND", numeric: "356", name: "India" },
  { id: "IDN", numeric: "360", name: "Indonesia" },
  { id: "IRN", numeric: "364", name: "Iran", aliases: ["Iran, Islamic Republic of"] },
  { id: "IRQ", numeric: "368", name: "Iraq" },
  { id: "IRL", numeric: "372", name: "Ireland" },
  { id: "IMN", numeric: "833", name: "Isle of Man" },
  { id: "ISR", numeric: "376", name: "Israel" },
  { id: "ITA", numeric: "380", name: "Italy" },
  { id: "JAM", numeric: "388", name: "Jamaica" },
  { id: "JPN", numeric: "392", name: "Japan" },
  { id: "JEY", numeric: "832", name: "Jersey" },
  { id: "JOR", numeric: "400", name: "Jordan" },
  { id: "KAZ", numeric: "398", name: "Kazakhstan" },
  { id: "KEN", numeric: "404", name: "Kenya" },
  { id: "KIR", numeric: "296", name: "Kiribati" },
  { id: "PRK", numeric: "408", name: "North Korea", aliases: ["Korea, Democratic People's Republic of"] },
  { id: "KOR", numeric: "410", name: "South Korea", aliases: ["Korea, Republic of"] },
  { id: "KWT", numeric: "414", name: "Kuwait" },
  { id: "KGZ", numeric: "417", name: "Kyrgyzstan" },
  { id: "LAO", numeric: "418", name: "Laos", aliases: ["Lao People's Democratic Republic"] },
  { id: "LVA", numeric: "428", name: "Latvia" },
  { id: "LBN", numeric: "422", name: "Lebanon" },
  { id: "LSO", numeric: "426", name: "Lesotho" },
  { id: "LBR", numeric: "430", name: "Liberia" },
  { id: "LBY", numeric: "434", name: "Libya" },
  { id: "LIE", numeric: "438", name: "Liechtenstein" },
  { id: "LTU", numeric: "440", name: "Lithuania" },
  { id: "LUX", numeric: "442", name: "Luxembourg" },
  { id: "MAC", numeric: "446", name: "Macao" },
  { id: "MDG", numeric: "450", name: "Madagascar" },
  { id: "MWI", numeric: "454", name: "Malawi" },
  { id: "MYS", numeric: "458", name: "Malaysia" },
  { id: "MDV", numeric: "462", name: "Maldives" },
  { id: "MLI", numeric: "466", name: "Mali" },
  { id: "MLT", numeric: "470", name: "Malta" },
  { id: "MHL", numeric: "584", name: "Marshall Islands" },
  { id: "MTQ", numeric: "474", name: "Martinique" },
  { id: "MRT", numeric: "478", name: "Mauritania" },
  { id: "MUS", numeric: "480", name: "Mauritius" },
  { id: "MYT", numeric: "175", name: "Mayotte" },
  { id: "MEX", numeric: "484", name: "Mexico" },
  { id: "FSM", numeric: "583", name: "Micronesia", aliases: ["Micronesia, Federated States of"] },
  { id: "MDA", numeric: "498", name: "Moldova", aliases: ["Moldova, Republic of"] },
  { id: "MCO", numeric: "492", name: "Monaco" },
  { id: "MNG", numeric: "496", name: "Mongolia" },
  { id: "MNE", numeric: "499", name: "Montenegro" },
  { id: "MSR", numeric: "500", name: "Montserrat" },
  { id: "MAR", numeric: "504", name: "Morocco" },
  { id: "MOZ", numeric: "508", name: "Mozambique" },
  { id: "MMR", numeric: "104", name: "Myanmar", aliases: ["Burma"] },
  { id: "NAM", numeric: "516", name: "Namibia" },
  { id: "NRU", numeric: "520", name: "Nauru" },
  { id: "NPL", numeric: "524", name: "Nepal" },
  { id: "NLD", numeric: "528", name: "Netherlands", aliases: ["Netherlands, Kingdom of the"] },
  { id: "NCL", numeric: "540", name: "New Caledonia" },
  { id: "NZL", numeric: "554", name: "New Zealand" },
  { id: "NIC", numeric: "558", name: "Nicaragua" },
  { id: "NER", numeric: "562", name: "Niger" },
  { id: "NGA", numeric: "566", name: "Nigeria" },
  { id: "NIU", numeric: "570", name: "Niue" },
  { id: "NFK", numeric: "574", name: "Norfolk Island" },
  { id: "MKD", numeric: "807", name: "North Macedonia", aliases: ["Macedonia"] },
  { id: "MNP", numeric: "580", name: "Northern Mariana Islands" },
  { id: "NOR", numeric: "578", name: "Norway" },
  { id: "OMN", numeric: "512", name: "Oman" },
  { id: "PAK", numeric: "586", name: "Pakistan" },
  { id: "PLW", numeric: "585", name: "Palau" },
  { id: "PSE", numeric: "275", name: "Palestine", aliases: ["Palestine, State of"] },
  { id: "PAN", numeric: "591", name: "Panama" },
  { id: "PNG", numeric: "598", name: "Papua New Guinea" },
  { id: "PRY", numeric: "600", name: "Paraguay" },
  { id: "PER", numeric: "604", name: "Peru" },
  { id: "PHL", numeric: "608", name: "Philippines" },
  { id: "PCN", numeric: "612", name: "Pitcairn" },
  { id: "POL", numeric: "616", name: "Poland" },
  { id: "PRT", numeric: "620", name: "Portugal" },
  { id: "PRI", numeric: "630", name: "Puerto Rico" },
  { id: "QAT", numeric: "634", name: "Qatar" },
  { id: "REU", numeric: "638", name: "Réunion" },
  { id: "ROU", numeric: "642", name: "Romania" },
  { id: "RUS", numeric: "643", name: "Russia", aliases: ["Russian Federation"] },
  { id: "RWA", numeric: "646", name: "Rwanda" },
  { id: "BLM", numeric: "652", name: "Saint Barthélemy" },
  { id: "SHN", numeric: "654", name: "Saint Helena, Ascension and Tristan da Cunha" },
  { id: "KNA", numeric: "659", name: "Saint Kitts and Nevis" },
  { id: "LCA", numeric: "662", name: "Saint Lucia" },
  { id: "MAF", numeric: "663", name: "Saint Martin (French part)" },
  { id: "SPM", numeric: "666", name: "Saint Pierre and Miquelon" },
  { id: "VCT", numeric: "670", name: "Saint Vincent and the Grenadines" },
  { id: "WSM", numeric: "882", name: "Samoa" },
  { id: "SMR", numeric: "674", name: "San Marino" },
  { id: "STP", numeric: "678", name: "Sao Tome and Principe" },
  { id: "SAU", numeric: "682", name: "Saudi Arabia" },
  { id: "SEN", numeric: "686", name: "Senegal" },
  { id: "SRB", numeric: "688", name: "Serbia" },
  { id: "SYC", numeric: "690", name: "Seychelles" },
  { id: "SLE", numeric: "694", name: "Sierra Leone" },
  { id: "SGP", numeric: "702", name: "Singapore" },
  { id: "SXM", numeric: "534", name: "Sint Maarten (Dutch part)" },
  { id: "SVK", numeric: "703", name: "Slovakia" },
  { id: "SVN", numeric: "705", name: "Slovenia" },
  { id: "SLB", numeric: "090", name: "Solomon Islands" },
  { id: "SOM", numeric: "706", name: "Somalia" },
  { id: "ZAF", numeric: "710", name: "South Africa" },
  { id: "SGS", numeric: "239", name: "South Georgia and the South Sandwich Islands" },
  { id: "SSD", numeric: "728", name: "South Sudan" },
  { id: "ESP", numeric: "724", name: "Spain" },
  { id: "LKA", numeric: "144", name: "Sri Lanka" },
  { id: "SDN", numeric: "729", name: "Sudan" },
  { id: "SUR", numeric: "740", name: "Suriname" },
  { id: "SJM", numeric: "744", name: "Svalbard and Jan Mayen" },
  { id: "SWE", numeric: "752", name: "Sweden" },
  { id: "CHE", numeric: "756", name: "Switzerland" },
  { id: "SYR", numeric: "760", name: "Syria", aliases: ["Syrian Arab Republic"] },
  { id: "TWN", numeric: "158", name: "Taiwan", aliases: ["Taiwan, Province of China"] },
  { id: "TJK", numeric: "762", name: "Tajikistan" },
  { id: "TZA", numeric: "834", name: "Tanzania", aliases: ["Tanzania, United Republic of"] },
  { id: "THA", numeric: "764", name: "Thailand" },
  { id: "TLS", numeric: "626", name: "Timor-Leste" },
  { id: "TGO", numeric: "768", name: "Togo" },
  { id: "TKL", numeric: "772", name: "Tokelau" },
  { id: "TON", numeric: "776", name: "Tonga" },
  { id: "TTO", numeric: "780", name: "Trinidad and Tobago" },
  { id: "TUN", numeric: "788", name: "Tunisia" },
  { id: "TUR", numeric: "792", name: "Turkey", aliases: ["Türkiye"] },
  { id: "TKM", numeric: "795", name: "Turkmenistan" },
  { id: "TCA", numeric: "796", name: "Turks and Caicos Islands" },
  { id: "TUV", numeric: "798", name: "Tuvalu" },
  { id: "UGA", numeric: "800", name: "Uganda" },
  { id: "UKR", numeric: "804", name: "Ukraine" },
  { id: "ARE", numeric: "784", name: "United Arab Emirates", aliases: ["UAE", "Emirates"] },
  { id: "GBR", numeric: "826", name: "United Kingdom", aliases: ["UK", "Great Britain", "Britain", "United Kingdom of Great Britain and Northern Ireland"] },
  { id: "USA", numeric: "840", name: "United States", aliases: ["USA", "US", "United States of America"] },
  { id: "UMI", numeric: "581", name: "United States Minor Outlying Islands" },
  { id: "URY", numeric: "858", name: "Uruguay" },
  { id: "UZB", numeric: "860", name: "Uzbekistan" },
  { id: "VUT", numeric: "548", name: "Vanuatu" },
  { id: "VEN", numeric: "862", name: "Venezuela", aliases: ["Venezuela, Bolivarian Republic of"] },
  { id: "VNM", numeric: "704", name: "Vietnam", aliases: ["Viet Nam"] },
  { id: "VGB", numeric: "092", name: "Virgin Islands (British)" },
  { id: "VIR", numeric: "850", name: "Virgin Islands (U.S.)" },
  { id: "WLF", numeric: "876", name: "Wallis and Futuna" },
  { id: "ESH", numeric: "732", name: "Western Sahara" },
  { id: "YEM", numeric: "887", name: "Yemen" },
  { id: "ZMB", numeric: "894", name: "Zambia" },
  { id: "ZWE", numeric: "716", name: "Zimbabwe" },
];
